# Configuration file for Detect.id
# This file defines the parameters and settings for the system.

# Set prediction hours 
prediction_hours: [24,48,72,96]

# 1 -> Train models 0 -> Load pickle files
train_models: 0

general_settings:
  num_thresholds: 3  # This must match the number of thresholds defined in each parameter.
  num_states: 3 # This must match the number of names, colors and thresholds of states
  name_states: ['Estável', 'Moderado', 'Emergência'] # Must be ordered from best to worst state.
  color_states: ['#129716', '#E8A310', '#c91515'] # Must be ordered from best to worst state.
  thresholds_states: [0.6,0.4] # Must be ordered from best to worst state.

graph_settings:
  graph_color_thresholds: ['blue', 'orangered', 'darkgreen'] # Color of the lines of the graphs 
  graph_color_states: ['green', 'yellow', 'red'] # Color of the areas representing the states (should be similar to color_states)
  graph_color_points: ['dodgerblue','gray'] # Color of the points that represent the pacient and the prevision

# Define the events that will be monitored, they must exist in the csv file.
events: ['Descompensação','Ativação Médico', 'Aumento da Vigilância', 'Via Área Ameaçada','Suporte Ventilatório', 'Suporte Circulatório', 'Mortalidade' ]

# Define the parameters to be monitored, they must exist in the csv file.
# Each parameter has a name, an abbreviation, a unit of measurement, thresholds.
# The number of thresholds must be the same defined in general settings.
parameters:
  - name: 'SpO2' # CSV Name
    abv_name: 'SpO2' # Name abreviation
    full_name: 'Saturação de Oxigênio' # Full Name
    unit_measurement: '%' #Unit measurement
    thresholds: [96,91] # Thresholds for intervals

  - name: 'Necessidade de O2'
    abv_name: 'O2'
    full_name: 'Necessidade de Oxigênio'
    unit_measurement: 'Sim/Não'
    thresholds: [1,0]

  - name: 'Frequência Cardíaca'
    abv_name: 'FC'
    full_name: 'Frequência Cardíaca'
    unit_measurement: 'bpm'
    thresholds: [110,51]
  
  - name: 'TA Sistólica'
    abv_name: 'TAS'
    full_name: 'Tensão Arterial Sistólica'
    unit_measurement: 'mmHg'
    thresholds: [130,110]
  
  - name: 'TA Diastólica'
    abv_name: 'TAD'
    full_name: 'Tensão Arterial Diastólica'
    unit_measurement: 'mmHg'
    thresholds: [80,60]
  
  - name: 'Temperatura'
    abv_name: 'Temp'
    full_name: 'Temperatura Corporal'
    unit_measurement: '°C'
    thresholds: [38,36]
  
  - name: 'Nível de Consciência'
    abv_name: 'GCS'
    full_name: 'Nível de Consciência (GCS)'
    unit_measurement: '1 a 15'
    thresholds: [15,8]
  
  - name: 'Dor'
    abv_name: 'Dor'
    full_name: 'Presença de Dor'
    unit_measurement: 'Sim/Não'
    thresholds: [1,0]

  # - name: 'Frequência Respiratória'
  #   abv_name: 'FR'
  #   full_name: 'Frequência Respiratória'
  #   unit_measurement: 'cr/m'
  #   thresholds: [20,10]
   
