# Generated by Django 5.1.7 on 2025-04-15 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.AutoField(primary_key=True, serialize=False)),
                ('gender_concept_id', models.IntegerField()),
                ('person_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observation_id', models.AutoField(primary_key=True, serialize=False)),
                ('observation_concept_id', models.IntegerField()),
                ('value_as_number', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('observation_datetime', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utentes.person')),
            ],
            options={
                'db_table': 'observation',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.AutoField(primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('note_type_concept_id', models.IntegerField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utentes.person')),
            ],
            options={
                'db_table': 'note',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.AutoField(primary_key=True, serialize=False)),
                ('measurement_concept_id', models.IntegerField()),
                ('value_as_number', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('measurement_datetime', models.DateTimeField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utentes.person')),
            ],
            options={
                'db_table': 'measurement',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ConditionOccurrence',
            fields=[
                ('condition_occurrence_id', models.AutoField(primary_key=True, serialize=False)),
                ('condition_start_date', models.DateField()),
                ('condition_source_value', models.CharField(max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utentes.person')),
            ],
            options={
                'db_table': 'condition_occurrence',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='VisitOccurrence',
            fields=[
                ('visit_occurrence_id', models.AutoField(primary_key=True, serialize=False)),
                ('care_site_id', models.IntegerField()),
                ('visit_start_datetime', models.DateTimeField()),
                ('visit_end_datetime', models.DateTimeField(blank=True, null=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utentes.person')),
            ],
            options={
                'db_table': 'visit_occurrence',
                'managed': True,
            },
        ),
    ]
