# Generated by Django 5.1.7 on 2025-04-11 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CareSite',
            fields=[
                ('care_site_id', models.IntegerField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'care_site',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConditionOccurrence',
            fields=[
                ('condition_occurrence_id', models.IntegerField(primary_key=True, serialize=False)),
                ('condition_start_date', models.DateField()),
                ('condition_source_value', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'condition_occurrence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Measurement',
            fields=[
                ('measurement_id', models.IntegerField(primary_key=True, serialize=False)),
                ('measurement_concept_id', models.IntegerField()),
                ('value_as_number', models.DecimalField(decimal_places=65535, max_digits=65535)),
                ('measurement_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'measurement',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('note_id', models.IntegerField(primary_key=True, serialize=False)),
                ('note_text', models.TextField()),
                ('note_type_concept_id', models.IntegerField()),
            ],
            options={
                'db_table': 'note',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Observation',
            fields=[
                ('observation_id', models.IntegerField(primary_key=True, serialize=False)),
                ('observation_concept_id', models.IntegerField()),
                ('value_as_number', models.DecimalField(blank=True, decimal_places=65535, max_digits=65535, null=True)),
                ('observation_datetime', models.DateTimeField()),
            ],
            options={
                'db_table': 'observation',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('person_id', models.IntegerField(primary_key=True, serialize=False)),
                ('gender_concept_id', models.IntegerField()),
                ('year_of_birth', models.IntegerField()),
                ('month_of_birth', models.IntegerField(blank=True, null=True)),
                ('day_of_birth', models.IntegerField(blank=True, null=True)),
                ('person_source_value', models.CharField(blank=True, max_length=50, null=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UtentesUtente',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('gender', models.CharField(max_length=255)),
                ('risk', models.CharField(max_length=255)),
                ('birthday', models.DateField()),
            ],
            options={
                'db_table': 'utentes_utente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='VisitOccurrence',
            fields=[
                ('visit_occurrence_id', models.IntegerField(primary_key=True, serialize=False)),
                ('visit_start_datetime', models.DateTimeField()),
                ('visit_end_datetime', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'visit_occurrence',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='PersonDetails',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='utentes.person')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'person_details',
                'managed': False,
            },
        ),
    ]
