# Generated by Django 5.1.7 on 2025-06-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caresite',
            name='care_site_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
