# Generated by Django 5.1.7 on 2025-06-13 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0002_alter_caresite_care_site_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='person',
            new_name='person_id',
        ),
    ]
