# Generated by Django 5.1.7 on 2025-05-12 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0002_authgroup_authgrouppermissions_authpermission_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='conditionoccurrence',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='hdregions',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='measurementext',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='personext',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='visitoccurrence',
            options={'managed': True},
        ),
    ]
