# Generated by Django 5.1.7 on 2025-04-13 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0002_caresite_conditionoccurrence_measurement_note_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonDetails',
        ),
    ]
