# Generated by Django 5.1.7 on 2025-04-14 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0003_delete_persondetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Utente',
        ),
        migrations.AlterModelOptions(
            name='caresite',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='conditionoccurrence',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='measurement',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='observation',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='utentesutente',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='visitoccurrence',
            options={'managed': True},
        ),
    ]
