# Generated by Django 5.1.7 on 2025-06-13 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utentes', '0003_rename_person_measurement_person_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurement',
            old_name='person_id',
            new_name='person',
        ),
    ]
